language: php

php:
    - hhvm

before_script:
    - composer self-update
    - composer update

script:
    - php vendor/bin/phpunit

after_script:
    - wget https://tomzx.github.io/php-semver-checker-git/php-semver-checker-git.phar
    - php php-semver-checker-git.phar suggest src src --allow-detached -vvv
